name: Upgrade to latest versions

on:
  workflow_dispatch:
  schedule:
    - cron: '37 7 * * 1'
jobs:
  versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - 'master'
    steps:
    - uses: actions/checkout@v2
      with:
        repository: arajkumar/cluster-monitoring-operator
        ref: ${{ matrix.branch }}
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Update jsonnet dependencies
      run: |
        make update
        make generate
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "[bot] [${{ matrix.branch }}] Automated version update"
        title: "[bot] [${{ matrix.branch }}] Automated version update"
        body: |
          ## Description
          This is an automated version and jsonnet dependencies update performed from CI.
        team-reviewers: kube-prometheus-reviewers
        committer: Prometheus Operator Bot <prom-op-bot@users.noreply.github.com>
        author: Prometheus Operator Bot <prom-op-bot@users.noreply.github.com>
        branch: automated-updates-${{ matrix.branch }}
        delete-branch: true
        token: ${{ steps.generate-token.outputs.token }}
        push-to-fork: sthaha/cluster-monitoring-operator
