name: Upgrade to latest versions

on:
  workflow_dispatch:
  schedule:
    - cron: '37 7 * * 1'
jobs:
  versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - 'master'
    steps:   
    - uses: actions/checkout@v2
      with:
        repository: syncbot-io/nocode
        ref: ${{ matrix.branch }}
        # token: ${{secrets.PAT}}
        # token: ${{ steps.cloner.outputs.token }}
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Update jsonnet dependencies
      run: |
        date >> time.txt
    - name: pr creation app token
      id: pr
      uses: getsentry/action-github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: cloner app token
      id: cloner
      uses: getsentry/action-github-app-token@v1
      with:
        app_id: ${{ secrets.CLONER_APP_ID }}
        private_key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}        
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Add changes"
#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      with:
#        github_token: ${{ steps.cloner.outputs.token }}
#        branch: automated-updates-cmo-${{ matrix.branch }}
#        repository: arajkumar/nocode
#        force: true
    - name: Create Pull Request
      uses: arajkumar/create-pull-request@v3
      with:
        commit-message: "[bot] [${{ matrix.branch }}] Automated version update"
        title: "[bot] [${{ matrix.branch }}] Automated version update"
        body: |
          ## Description
          This is an automated version and jsonnet dependencies update performed from CI.
        committer: Prometheus Operator Bot <prom-op-bot@users.noreply.github.com>
        author: Prometheus Operator Bot <prom-op-bot@users.noreply.github.com>
        branch: automated-updates-cmo-${{ matrix.branch }}
        delete-branch: true
        # token: ${{ secrets.GITHUB_TOKEN }}
        token: ${{ steps.pr.outputs.token }}
        # token: ${{secrets.PAT}}
        push-to-fork: arajkumar/nocode
        push-to-fork-token: ${{ steps.cloner.outputs.token }}
