name: Upgrade to latest versions

on:
  workflow_dispatch:
  schedule:
    - cron: '37 7 * * 1'
jobs:
  versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - 'master'
    steps:
#    - uses: tibdex/github-app-token@v1
#      id: cloner
#      with:
#        app_id: ${{ secrets.CLONER_APP_ID }}
#        private_key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}      
    - uses: actions/checkout@v2
      with:
        repository: syncbot-io/nocode
        ref: ${{ matrix.branch }}
        # token: ${{secrets.PAT}}
        # token: ${{ steps.cloner.outputs.token }}
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Update jsonnet dependencies
      run: |
        date >> time.txt
#    - uses: tibdex/github-app-token@v1
#      id: generate-token
#      with:
#        app_id: ${{ secrets.APP_ID }}
#        private_key: ${{ secrets.APP_PRIVATE_KEY }}        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "[bot] [${{ matrix.branch }}] Automated version update"
        title: "[bot] [${{ matrix.branch }}] Automated version update"
        body: |
          ## Description
          This is an automated version and jsonnet dependencies update performed from CI.
        committer: Prometheus Operator Bot <prom-op-bot@users.noreply.github.com>
        author: Prometheus Operator Bot <prom-op-bot@users.noreply.github.com>
        branch: automated-updates-cmo-${{ matrix.branch }}
        delete-branch: true
        # token: ${{ secrets.GITHUB_TOKEN }}
        # token: ${{ steps.generate-token.outputs.token }}
        # token: ${{secrets.PAT}}
        # push-to-fork: arajkumar/nocode
